server:
  port: 8080

fileUploader:
  media:
    mediaFiles:
      useFileExt: false
      allowedExtValidator: ''
      downloadUrlPattern: http://localhost:8080/api/storage/files/%s
      fileStorage:
        directory: ${java.io.tmpdir}


spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone=UTC:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
